version: '3.8'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  app:
    build: ./backend
    ports:
      - "9900:9900"  # map host port 9900 to container port 9900
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    restart: always
    volumes:
      - ./backend:/app
    deploy:
      resources:
        limits:
          memory: 2G  # ML models need more memory
  frontend:
    build: ./frontend
    ports:
      - "3901:3000"  # Map localhost:3901 to container:3000
    depends_on:
      - app
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Preserve node_modules from being overwritten
    environment:
      - REACT_APP_API_URL=http://localhost:8080  # For browser clients